### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by Nerdyvedi** [mozpp/Background-Matting#5]
Hi, Could you let me know the inference time you are getting with this model, at what resolution and on which device, please share the details as well.
Thanks a lot.

**Comment by mozpp** [comment]
> Hi, Could you let me know the inference time you are getting with this model, at what resolution and on which device, please share the details as well.
> Thanks a lot.

30fps for model inference.
288*288.
device: 1660

**Comment by Nerdyvedi** [comment]
Thanks a lot
